# Generated by Django 6.0.1 on 2026-01-24 15:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('attribute_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text="Stable machine-readable code (e.g., 'storage_tb')", max_length=100)),
                ('label', models.CharField(help_text="User-facing label (e.g., 'Storage Capacity')", max_length=255)),
            ],
            options={
                'db_table': 'pricing_attribute',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrape_sources', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CEX', 'CEX'), ('eBay', 'eBay'), ('CashConverters', 'CashConverters'), ('CashGenerator', 'CashGenerator')], help_text='Select which competitor sites to scrape for this category.', max_length=200)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base_margin', models.FloatField(default=0.0)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompetitorListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitor', models.CharField(choices=[('CeX', 'CeX'), ('CashConverters', 'CashConverters'), ('CashGenerator', 'CashGenerator'), ('eBay', 'eBay')], max_length=50)),
                ('stable_id', models.CharField(db_index=True, max_length=100)),
                ('store_name', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('condition', models.CharField(blank=True, max_length=255, null=True)),
                ('trade_voucher_price', models.FloatField(blank=True, null=True)),
                ('trade_cash_price', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConditionGrade',
            fields=[
                ('condition_grade_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text="Condition code (e.g., 'BOXED', 'UNBOXED', 'DISCOUNTED')", max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Condition Grade',
                'verbose_name_plural': 'Condition Grades',
                'db_table': 'pricing_condition_grade',
            },
        ),
        migrations.CreateModel(
            name='GlobalMarginRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('condition', 'Condition'), ('demand', 'Demand')], max_length=20)),
                ('match_value', models.CharField(max_length=100)),
                ('adjustment', models.FloatField(help_text='e.g. 0.10 for +10%, -0.05 for -5%')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MarginCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base_margin', models.FloatField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PawnShopAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_number', models.CharField(max_length=50, unique=True)),
                ('created_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('previous_agreements', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=100)),
                ('customer', models.CharField(max_length=255)),
                ('days_gone_past_expiry', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('attribute_value_id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(db_index=True, max_length=255)),
                ('attribute', models.ForeignKey(db_column='attribute_id', on_delete=django.db.models.deletion.CASCADE, related_name='values', to='pricing.attribute')),
            ],
            options={
                'db_table': 'pricing_attribute_value',
            },
        ),
        migrations.CreateModel(
            name='CategoryAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'storage'", max_length=100)),
                ('label', models.CharField(help_text="e.g. 'Storage Capacity'", max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('select', 'Select'), ('boolean', 'Boolean')], max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('options', models.JSONField(blank=True, help_text="For 'select' type: ['64GB','128GB']", null=True)),
                ('order', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='pricing.category')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CompetitorListingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('trade_voucher_price', models.FloatField(blank=True, null=True)),
                ('trade_cash_price', models.FloatField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('condition', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='pricing.competitorlisting')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('buyback_storage', 'Buyback Storage'), ('free_stock', 'Free Stock'), ('sold', 'Sold'), ('reserved', 'Reserved')], default='buyback_storage', max_length=50)),
                ('buyback_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('suggested_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_listing_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='pricing.category')),
            ],
        ),
        migrations.CreateModel(
            name='ItemModelAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.CharField(blank=True, max_length=255, null=True)),
                ('value_number', models.FloatField(blank=True, null=True)),
                ('value_boolean', models.BooleanField(default=False)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.categoryattribute')),
                ('item_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='pricing.itemmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform', models.CharField(blank=True, help_text='Where this item is listed, e.g. eBay, Website, etc.', max_length=100)),
                ('url', models.URLField(blank=True, null=True)),
                ('branch', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.OneToOneField(help_text='The inventory item currently listed for sale', on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='pricing.inventoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='ListingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user_margin', models.DecimalField(decimal_places=2, default=37.5, max_digits=5)),
                ('market_range', models.CharField(blank=True, max_length=50)),
                ('market_average', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cex_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cex_discounted', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rrp_with_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cc_lowest', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cc_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cg_lowest', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cg_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cc_recommended_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cg_recommended_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reasoning', models.TextField(blank=True)),
                ('competitors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(help_text='The listing this snapshot belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='pricing.listing')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarginRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('subcategory', 'Subcategory'), ('model', 'Model')], max_length=20)),
                ('match_value', models.CharField(max_length=100)),
                ('adjustment', models.FloatField()),
                ('description', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='pricing.category')),
            ],
            options={
                'ordering': ['category', 'order', 'rule_type'],
            },
        ),
        migrations.CreateModel(
            name='MarketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('last_scraped', models.DateTimeField(blank=True, null=True)),
                ('exclude_keywords', models.JSONField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_items', to='pricing.category')),
                ('item_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_items', to='pricing.itemmodel')),
            ],
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='market_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='pricing.marketitem'),
        ),
        migrations.AddField(
            model_name='competitorlisting',
            name='market_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='pricing.marketitem'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='pricing.pawnshopagreement'),
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('parent_category', models.ForeignKey(blank=True, db_column='parent_category_id', help_text='Parent category. Root categories point to themselves.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pricing.productcategory')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'db_table': 'pricing_product_category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='pricing.productcategory')),
            ],
            options={
                'db_table': 'pricing_product',
            },
        ),
        migrations.AddField(
            model_name='attribute',
            name='category',
            field=models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='pricing.productcategory'),
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='pricing.category')),
            ],
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='pricing.subcategory'),
        ),
        migrations.CreateModel(
            name='CEXPricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_class', models.CharField(choices=[('slow', 'Slow Moving'), ('medium', 'Medium Moving'), ('fast', 'Fast Moving')], default='medium', max_length=10)),
                ('cex_pct', models.FloatField(help_text='Percentage of CEX price to sell at, e.g., 0.8 for 80%')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cex_rules', to='pricing.category')),
                ('item_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cex_rules', to='pricing.itemmodel')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cex_rules', to='pricing.subcategory')),
            ],
            options={
                'ordering': ['category', 'subcategory', 'item_model', 'movement_class'],
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('variant_id', models.AutoField(primary_key=True, serialize=False)),
                ('cex_sku', models.CharField(db_index=True, help_text='CeX SKU - stable identity', max_length=100, unique=True)),
                ('current_price_gbp', models.DecimalField(decimal_places=2, help_text='Current price in GBP (denormalized for fast reads)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('tradein_cash', models.DecimalField(decimal_places=2, help_text='Trade-in value paid as cash in GBP', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tradein_voucher', models.DecimalField(decimal_places=2, help_text='Trade-in value paid as voucher in GBP', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cex_price_last_updated_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the CeX price was last updated')),
                ('cex_out_of_stock', models.BooleanField(default=False, help_text='Indicates whether the variant is out of stock at CeX')),
                ('variant_signature', models.CharField(db_index=True, help_text="Unique signature encoding attribute values (e.g., 'storage=1TB|edition=Digital')", max_length=500)),
                ('title', models.CharField(help_text='Human-readable variant title / box name', max_length=255)),
                ('condition_grade', models.ForeignKey(db_column='condition_grade_id', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='pricing.conditiongrade')),
                ('product', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='pricing.product')),
            ],
            options={
                'db_table': 'pricing_variant',
            },
        ),
        migrations.CreateModel(
            name='VariantAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_value', models.ForeignKey(db_column='attribute_value_id', on_delete=django.db.models.deletion.CASCADE, related_name='variant_attribute_values', to='pricing.attributevalue')),
                ('variant', models.ForeignKey(db_column='variant_id', on_delete=django.db.models.deletion.CASCADE, related_name='variant_attribute_values', to='pricing.variant')),
            ],
            options={
                'db_table': 'pricing_variant_attribute_value',
            },
        ),
        migrations.AddField(
            model_name='variant',
            name='attribute_values',
            field=models.ManyToManyField(related_name='variants', through='pricing.VariantAttributeValue', to='pricing.attributevalue'),
        ),
        migrations.CreateModel(
            name='VariantPriceHistory',
            fields=[
                ('price_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('price_gbp', models.DecimalField(decimal_places=2, help_text='Price in GBP at this point in time', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this price was recorded')),
                ('variant', models.ForeignKey(db_column='variant_id', on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='pricing.variant')),
            ],
            options={
                'db_table': 'pricing_variant_price_history',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='VariantStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DELISTED', 'Delisted'), ('DISCONTINUED', 'Discontinued')], db_index=True, max_length=20)),
                ('effective_from', models.DateTimeField(db_index=True, help_text='When this status became effective')),
                ('variant', models.ForeignKey(db_column='variant_id', on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='pricing.variant')),
            ],
            options={
                'db_table': 'pricing_variant_status',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.AddIndex(
            model_name='attributevalue',
            index=models.Index(fields=['attribute', 'value'], name='pricing_att_attribu_bc3a56_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attributevalue',
            unique_together={('attribute', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='categoryattribute',
            unique_together={('category', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='itemmodelattributevalue',
            unique_together={('item_model', 'attribute')},
        ),
        migrations.AlterUniqueTogether(
            name='marketitem',
            unique_together={('category', 'title', 'item_model')},
        ),
        migrations.AlterUniqueTogether(
            name='competitorlisting',
            unique_together={('market_item', 'competitor', 'stable_id')},
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['parent_category', 'name'], name='pricing_pro_parent__ce1b9c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'name'], name='pricing_pro_categor_77fb0a_idx'),
        ),
        migrations.AddIndex(
            model_name='attribute',
            index=models.Index(fields=['category', 'code'], name='pricing_att_categor_3c8e4b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together={('category', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='itemmodel',
            unique_together={('subcategory', 'name')},
        ),
        migrations.AddConstraint(
            model_name='cexpricingrule',
            constraint=models.UniqueConstraint(fields=('category', 'subcategory', 'item_model', 'movement_class'), name='unique_rule_per_scope_and_movement'),
        ),
        migrations.AddIndex(
            model_name='variantattributevalue',
            index=models.Index(fields=['variant', 'attribute_value'], name='pricing_var_variant_ad1da5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='variantattributevalue',
            unique_together={('variant', 'attribute_value')},
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['product', 'condition_grade'], name='pricing_var_product_30cb23_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['cex_sku'], name='pricing_var_cex_sku_f003e7_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['current_price_gbp'], name='pricing_var_current_1173c8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='variant',
            unique_together={('product', 'condition_grade', 'variant_signature')},
        ),
        migrations.AddIndex(
            model_name='variantpricehistory',
            index=models.Index(fields=['variant', '-recorded_at'], name='pricing_var_variant_5b031b_idx'),
        ),
        migrations.AddIndex(
            model_name='variantpricehistory',
            index=models.Index(fields=['recorded_at'], name='pricing_var_recorde_fd7efe_idx'),
        ),
        migrations.AddIndex(
            model_name='variantstatus',
            index=models.Index(fields=['variant', '-effective_from'], name='pricing_var_variant_5d0c08_idx'),
        ),
        migrations.AddIndex(
            model_name='variantstatus',
            index=models.Index(fields=['status', 'effective_from'], name='pricing_var_status_339940_idx'),
        ),
    ]
