# Generated by Django 6.0.1 on 2026-01-24 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variant',
            unique_together={('product', 'condition_grade', 'variant_signature', 'title')},
        ),
    ]
