# Generated by Django 6.0.1 on 2026-01-24 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_alter_variant_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variant',
            unique_together=set(),
        ),
    ]
