# Generated by Django 5.2.6 on 2026-01-26 12:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_alter_variant_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, db_column='parent_category_id', help_text='Parent category. Root categories have this empty.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pricing.productcategory'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text="Stable location code (e.g., 'WARR', 'WYTH')", max_length=50, unique=True)),
                ('name', models.CharField(help_text='Human-readable location name', max_length=255)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'db_table': 'pricing_location',
                'indexes': [models.Index(fields=['code'], name='pricing_loc_code_b8e221_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventoryUnit',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_number', models.CharField(blank=True, db_index=True, help_text='Optional serial number or IMEI', max_length=255, null=True)),
                ('acquired_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this item was acquired')),
                ('is_sellable', models.BooleanField(default=True, help_text='Whether this specific item can currently be sold')),
                ('notes', models.TextField(blank=True, help_text='Free-form notes about this unit')),
                ('variant', models.ForeignKey(db_column='variant_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pricing.variant')),
                ('location', models.ForeignKey(db_column='location_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pricing.location')),
            ],
            options={
                'db_table': 'pricing_inventory_item',
                'indexes': [models.Index(fields=['variant', 'location'], name='pricing_inv_variant_561530_idx'), models.Index(fields=['serial_number'], name='pricing_inv_serial__126b6a_idx'), models.Index(fields=['is_sellable'], name='pricing_inv_is_sell_f5141d_idx')],
            },
        ),
        migrations.CreateModel(
            name='VariantInventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_on_hand', models.PositiveIntegerField(default=0, help_text='Physical stock currently held')),
                ('quantity_reserved', models.PositiveIntegerField(default=0, help_text='Stock reserved for orders but not yet fulfilled')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='When this inventory row was last updated')),
                ('location', models.ForeignKey(db_column='location_id', on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='pricing.location')),
                ('variant', models.ForeignKey(db_column='variant_id', on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='pricing.variant')),
            ],
            options={
                'db_table': 'pricing_variant_inventory',
                'indexes': [models.Index(fields=['variant', 'location'], name='pricing_var_variant_a53a68_idx'), models.Index(fields=['location'], name='pricing_var_locatio_54fd36_idx')],
                'unique_together': {('variant', 'location')},
            },
        ),
    ]
