# Generated by Django 5.2.6 on 2026-01-26 20:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_alter_productcategory_parent_category_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='product',
            field=models.ForeignKey(db_column='product_id', default=0, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='pricing.product'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('pricing_rule_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_global_default', models.BooleanField(default=False, help_text='Fallback rule if no product or category rule exists')),
                ('movement_class', models.CharField(choices=[('FAST', 'Fast mover'), ('MEDIUM', 'Medium mover'), ('SLOW', 'Slow mover'), ('UNKNOWN', 'Unknown')], db_index=True, max_length=20)),
                ('sell_price_multiplier', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='pricing.productcategory')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='pricing.product')),
            ],
            options={
                'db_table': 'pricing_rule',
                'indexes': [models.Index(fields=['product', 'movement_class'], name='pricing_rul_product_0efe47_idx'), models.Index(fields=['category', 'movement_class'], name='pricing_rul_categor_04488e_idx'), models.Index(fields=['is_global_default', 'movement_class'], name='pricing_rul_is_glob_9bd63d_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('product__isnull', False)), fields=('product', 'movement_class'), name='uniq_product_movement_rule'), models.UniqueConstraint(condition=models.Q(('category__isnull', False)), fields=('category', 'movement_class'), name='uniq_category_movement_rule'), models.UniqueConstraint(condition=models.Q(('is_global_default', True)), fields=('movement_class',), name='uniq_global_default_movement_rule'), models.CheckConstraint(condition=models.Q(('product__isnull', False), ('category__isnull', False), ('is_global_default', True), _connector='OR'), name='pricing_rule_scope_required')],
            },
        ),
    ]
