# Generated by Django 5.2.6 on 2026-01-27 13:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_alter_variant_product_pricingrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(db_index=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'buying_customer',
            },
        ),
        migrations.CreateModel(
            name='InventoryOwnershipEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ACQUIRED_DIRECT', 'Acquired Direct'), ('BUYBACK_STARTED', 'Buyback Started'), ('BUYBACK_EXERCISED', 'Buyback Exercised'), ('BUYBACK_EXPIRED', 'Buyback Expired')], max_length=30)),
                ('event_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('inventory_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_events', to='pricing.inventoryunit')),
            ],
            options={
                'db_table': 'inventory_ownership_event',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('intent', models.CharField(choices=[('BUYBACK', 'Buyback'), ('DIRECT_SALE', 'Direct Sale'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='pricing.customer')),
            ],
            options={
                'db_table': 'buying_request',
            },
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('request_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('initial_expectation_gbp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pricing.request')),
                ('variant', models.ForeignKey(blank=True, help_text='Resolved variant after identification', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.variant')),
            ],
            options={
                'db_table': 'buying_request_item',
            },
        ),
        migrations.CreateModel(
            name='RequestStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CONTACTED', 'Contacted'), ('BOOKED_FOR_TESTING', 'Booked For Testing'), ('TESTING_COMPLETE', 'Testing Complete'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], max_length=30)),
                ('effective_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='pricing.request')),
            ],
            options={
                'db_table': 'buying_request_status',
                'ordering': ['-effective_at'],
            },
        ),
        migrations.CreateModel(
            name='TradeIn',
            fields=[
                ('tradein_id', models.AutoField(primary_key=True, serialize=False)),
                ('final_offer_gbp', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('outcome', models.CharField(choices=[('BUYBACK', 'Buyback'), ('DIRECT_SALE', 'Direct Sale')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tradein', to='pricing.requestitem')),
            ],
            options={
                'db_table': 'buying_tradein',
            },
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('agreement_id', models.AutoField(primary_key=True, serialize=False)),
                ('agreement_type', models.CharField(choices=[('DIRECT_SALE', 'Direct Sale'), ('BUYBACK', 'Buyback')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXERCISED', 'Exercised'), ('EXPIRED', 'Expired'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=20)),
                ('signed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Only for buyback agreements', null=True)),
                ('buyback_repurchase_gbp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tradein', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agreement', to='pricing.tradein')),
            ],
            options={
                'db_table': 'buying_agreement',
            },
        ),
        migrations.AddField(
            model_name='inventoryunit',
            name='tradein',
            field=models.OneToOneField(default=0, help_text='Trade-in that created this physical item', on_delete=django.db.models.deletion.PROTECT, related_name='inventory_unit', to='pricing.tradein'),
            preserve_default=False,
        ),
    ]
