# Generated by Django 6.0.1 on 2026-01-31 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0007_customer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('manufacturer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
            options={
                'db_table': 'pricing_manufacturer',
            },
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='requeststatushistory',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('BOOKED_FOR_TESTING', 'Booked For Testing'), ('TESTING_COMPLETE', 'Testing Complete'), ('CANCELLED', 'Cancelled')], max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(blank=True, db_column='manufacturer_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='pricing.manufacturer'),
        ),
    ]
