# Generated by Django 6.0.1 on 2026-02-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0008_manufacturer_alter_customer_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='intent',
            field=models.CharField(choices=[('BUYBACK', 'Buyback'), ('DIRECT_SALE', 'Direct Sale'), ('STORE_CREDIT', 'Store Credit'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20),
        ),
    ]
