# Generated by Django 6.0.1 on 2026-02-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0009_alter_request_intent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestitem',
            name='initial_expectation_gbp',
        ),
        migrations.AddField(
            model_name='request',
            name='overall_expectation_gbp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Overall expectation for the request', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='requestitem',
            name='expectation_gbp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expectation for this item', max_digits=10, null=True),
        ),
    ]
