# Generated by Django 6.0.1 on 2026-02-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0010_remove_requestitem_initial_expectation_gbp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestitem',
            name='raw_data',
            field=models.JSONField(blank=True, help_text='Raw data used for pricing decisions (for auditing/review purposes)', null=True),
        ),
    ]
