# Generated by Django 6.0.1 on 2026-02-07 12:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0012_remove_categoryattribute_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='negotiated_grand_total_gbp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Grand total of all negotiated item prices in GBP', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='requestitem',
            name='customer_expectation_gbp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Customer's expected price for this item", max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='requestitem',
            name='manual_offer_gbp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Manually entered offer price for this item', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='requestitem',
            name='negotiated_price_gbp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final negotiated price for this item after selection', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='requestitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Quantity of this item in the request'),
        ),
        migrations.AddField(
            model_name='requestitem',
            name='selected_offer_id',
            field=models.CharField(blank=True, help_text="ID of the offer selected for this item (e.g., 'manual', 'cash_1', 'voucher_2')", max_length=50, null=True),
        ),
    ]
