# Generated by Django 6.0.1 on 2026-02-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0013_request_negotiated_grand_total_gbp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestitem',
            name='cash_offers_json',
            field=models.JSONField(blank=True, help_text='Snapshot of cash offers presented during negotiation', null=True),
        ),
        migrations.AddField(
            model_name='requestitem',
            name='voucher_offers_json',
            field=models.JSONField(blank=True, help_text='Snapshot of voucher offers presented during negotiation', null=True),
        ),
    ]
