# Generated by Django 6.0.1 on 2026-02-07 17:16

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0014_requestitem_cash_offers_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestitem',
            name='cex_buy_cash_at_negotiation',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='CeX Buy (Cash) price at negotiation time', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='requestitem',
            name='cex_buy_voucher_at_negotiation',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='CeX Buy (Voucher) price at negotiation time', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='requestitem',
            name='cex_sell_at_negotiation',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='CeX Sell price at negotiation time', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
