# Generated by Django 6.0.1 on 2026-02-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0015_requestitem_cex_buy_cash_at_negotiation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestitem',
            name='our_sale_price_at_negotiation',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Our calculated sale price at the time of negotiation', max_digits=10, null=True),
        ),
    ]
