# Generated by Django 6.0.1 on 2026-02-10 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0017_update_request_status_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestitem',
            name='our_sale_price_at_negotiation',
        ),
    ]
