# Generated by Django 6.0.1 on 2026-02-10 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0018_remove_requestitem_our_sale_price_at_negotiation'),
        ('pricing', '0018_remove_unknown_from_request_intent'),
    ]

    operations = [
    ]
