# Generated by Django 6.0.1 on 2026-02-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0019_merge_20260210_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestitem',
            name='cash_converters_data',
            field=models.JSONField(blank=True, help_text='Cash Converters research data used for pricing decisions', null=True),
        ),
    ]
