# Generated by Django 6.0.1 on 2026-02-11 11:32

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0020_requestitem_cash_converters_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestitem',
            name='our_sale_price_at_negotiation',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Our calculated sale price at the time of negotiation', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
