# Generated by Django 6.0.2 on 2026-03-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0021_requestitem_our_sale_price_at_negotiation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_temp_staging',
            field=models.BooleanField(default=False),
        ),
    ]
