# Generated by Django 6.0.2 on 2026-03-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0022_customer_is_temp_staging'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestitem',
            name='manual_offer_used',
            field=models.BooleanField(default=False, help_text='True if a manual offer was set using the manual offer tool'),
        ),
        migrations.AddField(
            model_name='requestitem',
            name='senior_mgmt_approved_by',
            field=models.CharField(blank=True, help_text='Name of senior management who approved when offer exceeded sale price', max_length=255, null=True),
        ),
    ]
