# Generated by Django 5.2.7 on 2026-01-19 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0026_attribute_conditiongrade_attributevalue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='label',
            field=models.CharField(default=2, help_text="User-facing label (e.g., 'Storage Capacity')", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attribute',
            name='code',
            field=models.CharField(db_index=True, help_text="Stable machine-readable code (e.g., 'storage_tb')", max_length=100),
        ),
        migrations.AlterField(
            model_name='variant',
            name='product',
            field=models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='pricing.product'),
        ),
    ]
