# Generated by Django 5.2.7 on 2026-01-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0027_attribute_label_alter_attribute_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='title',
            field=models.CharField(default=2, help_text='Human-readable variant title / box name', max_length=255),
            preserve_default=False,
        ),
    ]
