# Generated by Django 5.2.7 on 2026-01-23 11:10

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0028_variant_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='tradein_cash',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Trade-in value paid as cash in GBP', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='tradein_voucher',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Trade-in value paid as voucher in GBP', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
            preserve_default=False,
        ),
    ]
