# Generated by Django 6.0.2 on 2026-03-18 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0029_remove_movement_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='customer_enrichment_json',
            field=models.JSONField(blank=True, help_text='Enriched customer data from NoSpos (rates, dates, etc.) for display in buyer UI', null=True),
        ),
    ]
