# Generated by Django 5.2.7 on 2026-01-23 11:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0029_variant_tradein_cash_variant_tradein_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='cex_out_of_stock',
            field=models.BooleanField(default=False, help_text='Indicates whether the variant is out of stock at CeX'),
        ),
        migrations.AddField(
            model_name='variant',
            name='cex_price_last_updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the CeX price was last updated'),
        ),
    ]
