# Generated by Django 6.0.2 on 2026-03-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0031_pricingrule_second_offer_pct_of_cex'),
    ]

    operations = [
        migrations.AddField(
            model_name='repricingsession',
            name='session_data',
            field=models.JSONField(blank=True, help_text='Full frontend state for resuming in-progress sessions (items, barcodes, lookups, research)', null=True),
        ),
        migrations.AddField(
            model_name='repricingsession',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], db_index=True, default='IN_PROGRESS', max_length=20),
        ),
        migrations.AddField(
            model_name='repricingsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
