# Generated by Django 6.0.2 on 2026-03-21 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0032_add_repricing_session_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingrule',
            name='ebay_offer_margin_1_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Margin % for the first eBay/research-based offer. E.g. 60 means offer = suggestedPrice * 0.40. Default 60.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='ebay_offer_margin_2_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Margin % for the second eBay/research-based offer. E.g. 50 means offer = suggestedPrice * 0.50. Default 50.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='ebay_offer_margin_3_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Margin % for the third eBay/research-based offer. E.g. 40 means offer = suggestedPrice * 0.60. Default 40.', max_digits=5, null=True),
        ),
    ]
