# Generated by Django 6.0.2 on 2026-03-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0034_ebay_offer_margins_to_pct_of_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingrule',
            name='ebay_offer_margin_1_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='First eBay/Cash Converters cash offer as % of suggested sale price. E.g. 40 means offer = suggestedPrice × 0.40. Default 40.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='ebay_offer_margin_2_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Second offer as % of suggested sale price. E.g. 50 means offer = suggestedPrice × 0.50. Default 50.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='ebay_offer_margin_3_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Third offer as % of suggested sale price. E.g. 60 means offer = suggestedPrice × 0.60. Default 60.', max_digits=5, null=True),
        ),
    ]
