# Generated by Django 6.0.2 on 2026-03-25 17:02

import copy
import django.db.models.deletion
from decimal import Decimal, InvalidOperation
from django.db import migrations, models


STANDARD_LISTING_KEYS = frozenset(
    {
        "_id",
        "title",
        "price",
        "url",
        "image",
        "sold",
        "itemId",
        "excluded",
        "shop",
        "sellerInfo",
    }
)


def _dec(val):
    if val is None:
        return None
    if isinstance(val, Decimal):
        return val
    try:
        if isinstance(val, str):
            val = val.replace("£", "").replace(",", "").strip()
        return Decimal(str(val))
    except (InvalidOperation, TypeError, ValueError):
        return None


def _parse_selected_offer_index(val):
    if val is None:
        return None
    if val == "manual":
        return "manual"
    if isinstance(val, (int, float)):
        return str(int(val))
    s = str(val).strip()
    return s if s else None


def _is_market_research_dict(d):
    if not isinstance(d, dict):
        return False
    if not isinstance(d.get("listings"), list):
        return False
    stats = d.get("stats")
    if not isinstance(stats, dict):
        return False
    return "median" in stats or "average" in stats or "suggestedPrice" in stats


def _is_cex_product_snapshot_dict(d):
    if not isinstance(d, dict):
        return False
    if d.get("id") in (None, "") or not d.get("title"):
        return False
    if _is_market_research_dict(d):
        return False
    return True


def _strip_known_keys(d, keys):
    extra = {k: v for k, v in d.items() if k not in keys}
    return extra if extra else None


def _replace_request_item_research(
    HistoricalMRSession,
    HistoricalMRListing,
    HistoricalMRDrill,
    request_item,
    platform,
    payload,
):
    HistoricalMRSession.objects.filter(request_item=request_item, platform=platform).delete()
    if not payload or not isinstance(payload, dict):
        return
    if not _is_market_research_dict(payload):
        return
    stats = payload.get("stats") or {}
    sel = payload.get("selectedFilters")
    filt_opts = payload.get("filterOptions")
    filter_state = None
    if sel is not None or filt_opts is not None:
        filter_state = {"selectedFilters": sel, "filterOptions": filt_opts}
    session = HistoricalMRSession.objects.create(
        request_item=request_item,
        repricing_session_item=None,
        platform=platform,
        search_term=str(payload.get("searchTerm") or "")[:500],
        listing_page_url=str(payload.get("listingPageUrl") or "")[:2000],
        show_histogram=bool(payload.get("showHistogram")),
        manual_offer_text=str(payload.get("manualOffer") or "")[:64],
        selected_offer_index=_parse_selected_offer_index(payload.get("selectedOfferIndex")),
        stat_average_gbp=_dec(stats.get("average")),
        stat_median_gbp=_dec(stats.get("median")),
        stat_suggested_sale_gbp=_dec(stats.get("suggestedPrice")),
        advanced_filter_state=payload.get("advancedFilterState"),
        filter_state_json=filter_state,
        buy_offers_json=payload.get("buyOffers"),
    )
    for idx, level in enumerate(payload.get("drillHistory") or []):
        if not isinstance(level, dict):
            continue
        da, db = _dec(level.get("min")), _dec(level.get("max"))
        if da is None or db is None:
            continue
        HistoricalMRDrill.objects.create(
            session=session,
            level_index=idx,
            min_gbp=da,
            max_gbp=db,
        )
    for order, row in enumerate(payload.get("listings") or []):
        if not isinstance(row, dict):
            continue
        extra = _strip_known_keys(row, STANDARD_LISTING_KEYS)
        HistoricalMRListing.objects.create(
            session=session,
            sort_order=order,
            client_row_id=str(row.get("_id") or "")[:128],
            external_item_id=str(row.get("itemId") or "")[:64],
            title=str(row.get("title") or ""),
            price_gbp=_dec(row.get("price")),
            listing_url=str(row.get("url") or "")[:2000],
            image_url=str(row.get("image") or "")[:2000] if row.get("image") else "",
            excluded=bool(row.get("excluded")),
            sold_text=str(row.get("sold") or "")[:256],
            shop_name=str(row.get("shop") or "")[:256],
            seller_info=str(row.get("sellerInfo") or "")[:2000],
            extra=extra,
        )


def _replace_repricing_research(
    HistoricalMRSession,
    HistoricalMRListing,
    HistoricalMRDrill,
    repricing_item,
    platform,
    payload,
):
    HistoricalMRSession.objects.filter(
        repricing_session_item=repricing_item, platform=platform
    ).delete()
    if not payload or not isinstance(payload, dict):
        return
    if not _is_market_research_dict(payload):
        return
    stats = payload.get("stats") or {}
    sel = payload.get("selectedFilters")
    filt_opts = payload.get("filterOptions")
    filter_state = None
    if sel is not None or filt_opts is not None:
        filter_state = {"selectedFilters": sel, "filterOptions": filt_opts}
    session = HistoricalMRSession.objects.create(
        request_item=None,
        repricing_session_item=repricing_item,
        platform=platform,
        search_term=str(payload.get("searchTerm") or "")[:500],
        listing_page_url=str(payload.get("listingPageUrl") or "")[:2000],
        show_histogram=bool(payload.get("showHistogram")),
        manual_offer_text=str(payload.get("manualOffer") or "")[:64],
        selected_offer_index=_parse_selected_offer_index(payload.get("selectedOfferIndex")),
        stat_average_gbp=_dec(stats.get("average")),
        stat_median_gbp=_dec(stats.get("median")),
        stat_suggested_sale_gbp=_dec(stats.get("suggestedPrice")),
        advanced_filter_state=payload.get("advancedFilterState"),
        filter_state_json=filter_state,
        buy_offers_json=payload.get("buyOffers"),
    )
    for idx, level in enumerate(payload.get("drillHistory") or []):
        if not isinstance(level, dict):
            continue
        da, db = _dec(level.get("min")), _dec(level.get("max"))
        if da is None or db is None:
            continue
        HistoricalMRDrill.objects.create(
            session=session,
            level_index=idx,
            min_gbp=da,
            max_gbp=db,
        )
    for order, row in enumerate(payload.get("listings") or []):
        if not isinstance(row, dict):
            continue
        extra = _strip_known_keys(row, STANDARD_LISTING_KEYS)
        HistoricalMRListing.objects.create(
            session=session,
            sort_order=order,
            client_row_id=str(row.get("_id") or "")[:128],
            external_item_id=str(row.get("itemId") or "")[:64],
            title=str(row.get("title") or ""),
            price_gbp=_dec(row.get("price")),
            listing_url=str(row.get("url") or "")[:2000],
            image_url=str(row.get("image") or "")[:2000] if row.get("image") else "",
            excluded=bool(row.get("excluded")),
            sold_text=str(row.get("sold") or "")[:256],
            shop_name=str(row.get("shop") or "")[:256],
            seller_info=str(row.get("sellerInfo") or "")[:2000],
            extra=extra,
        )


def _sync_raw_into_request_item(
    HistoricalMRSession,
    HistoricalMRListing,
    HistoricalMRDrill,
    item,
    raw,
):
    if not raw or not isinstance(raw, dict):
        return
    ref = raw.get("referenceData")
    if ref is None:
        ref = raw.get("reference_data")
    if ref is not None:
        item.cex_reference_json = ref
    meta = dict(item.line_metadata_json or {})
    for k in ("display_title", "display_subtitle"):
        if raw.get(k) is not None:
            meta[k] = raw[k]
    item.line_metadata_json = meta if meta else None

    ebay_src = None
    if _is_market_research_dict(raw):
        ebay_src = raw
    elif isinstance(raw.get("ebayResearchData"), dict) and _is_market_research_dict(
        raw["ebayResearchData"]
    ):
        ebay_src = raw["ebayResearchData"]
    if ebay_src:
        _replace_request_item_research(
            HistoricalMRSession,
            HistoricalMRListing,
            HistoricalMRDrill,
            item,
            "EBAY",
            ebay_src,
        )

    cc_embed = raw.get("cashConvertersResearchData")
    if isinstance(cc_embed, dict) and _is_market_research_dict(cc_embed):
        _replace_request_item_research(
            HistoricalMRSession,
            HistoricalMRListing,
            HistoricalMRDrill,
            item,
            "CASH_CONVERTERS",
            cc_embed,
        )

    if _is_cex_product_snapshot_dict(raw):
        strip_keys = {
            "referenceData",
            "reference_data",
            "ebayResearchData",
            "cashConvertersResearchData",
            "display_title",
            "display_subtitle",
        }
        snap = {k: v for k, v in raw.items() if k not in strip_keys}
        if not _is_market_research_dict(snap):
            item.cex_line_snapshot_json = snap


def forwards_migrate(apps, schema_editor):
    RequestItem = apps.get_model("pricing", "RequestItem")
    RepricingSessionItem = apps.get_model("pricing", "RepricingSessionItem")
    MRSession = apps.get_model("pricing", "MarketResearchSession")
    MRListing = apps.get_model("pricing", "MarketResearchListing")
    MRDrill = apps.get_model("pricing", "MarketResearchDrillLevel")

    for item in RequestItem.objects.all().iterator():
        raw = item.raw_data
        cc = item.cash_converters_data
        if isinstance(raw, dict) and raw:
            _sync_raw_into_request_item(
                MRSession, MRListing, MRDrill, item, copy.deepcopy(raw)
            )
        if isinstance(cc, dict) and cc:
            _replace_request_item_research(
                MRSession, MRListing, MRDrill, item, "CASH_CONVERTERS", copy.deepcopy(cc)
            )
        item.save(
            update_fields=[
                "cex_reference_json",
                "cex_line_snapshot_json",
                "line_metadata_json",
            ]
        )

    for line in RepricingSessionItem.objects.all().iterator():
        raw = line.raw_data
        cc = line.cash_converters_data
        if isinstance(raw, dict) and raw:
            _replace_repricing_research(
                MRSession, MRListing, MRDrill, line, "EBAY", copy.deepcopy(raw)
            )
        if isinstance(cc, dict) and cc:
            _replace_repricing_research(
                MRSession, MRListing, MRDrill, line, "CASH_CONVERTERS", copy.deepcopy(cc)
            )


def backwards_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0035_alter_pricingrule_ebay_offer_margin_1_pct_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestitem",
            name="cex_line_snapshot_json",
            field=models.JSONField(
                blank=True,
                help_text="Full 'Add from CeX' product payload when the line is a custom CeX item (non-catalog)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="requestitem",
            name="cex_reference_json",
            field=models.JSONField(
                blank=True,
                help_text="CeX reference bundle (pricing strip, images) attached to this line when eBay/CC research is saved",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="requestitem",
            name="line_metadata_json",
            field=models.JSONField(
                blank=True,
                help_text="Negotiation UI metadata (display_title, display_subtitle, etc.)",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="MarketResearchSession",
            fields=[
                ("session_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "platform",
                    models.CharField(
                        choices=[("EBAY", "eBay"), ("CASH_CONVERTERS", "Cash Converters")],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("search_term", models.CharField(blank=True, default="", max_length=500)),
                (
                    "listing_page_url",
                    models.URLField(blank=True, default="", max_length=2000),
                ),
                ("show_histogram", models.BooleanField(default=False)),
                (
                    "manual_offer_text",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "selected_offer_index",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "stat_average_gbp",
                    models.DecimalField(
                        blank=True,
                        db_index=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "stat_median_gbp",
                    models.DecimalField(
                        blank=True,
                        db_index=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "stat_suggested_sale_gbp",
                    models.DecimalField(
                        blank=True,
                        db_index=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("advanced_filter_state", models.JSONField(blank=True, null=True)),
                (
                    "filter_state_json",
                    models.JSONField(
                        blank=True,
                        help_text="selectedFilters, filterOptions-as-captured from the research form",
                        null=True,
                    ),
                ),
                (
                    "buy_offers_json",
                    models.JSONField(
                        blank=True,
                        help_text="Snapshot of calculated buy offers at save time (pctOfSale, price)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "repricing_session_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_research_sessions",
                        to="pricing.repricingsessionitem",
                    ),
                ),
                (
                    "request_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_research_sessions",
                        to="pricing.requestitem",
                    ),
                ),
            ],
            options={
                "db_table": "pricing_market_research_session",
            },
        ),
        migrations.CreateModel(
            name="MarketResearchListing",
            fields=[
                ("listing_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "sort_order",
                    models.PositiveIntegerField(db_index=True, default=0),
                ),
                (
                    "client_row_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "external_item_id",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                ("title", models.TextField(blank=True, default="")),
                (
                    "price_gbp",
                    models.DecimalField(
                        blank=True,
                        db_index=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "listing_url",
                    models.URLField(blank=True, default="", max_length=2000),
                ),
                (
                    "image_url",
                    models.URLField(blank=True, default="", max_length=2000),
                ),
                ("excluded", models.BooleanField(db_index=True, default=False)),
                (
                    "sold_text",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                (
                    "shop_name",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                ("seller_info", models.TextField(blank=True, default="")),
                ("extra", models.JSONField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to="pricing.marketresearchsession",
                    ),
                ),
            ],
            options={
                "db_table": "pricing_market_research_listing",
                "ordering": ["sort_order", "listing_id"],
            },
        ),
        migrations.CreateModel(
            name="MarketResearchDrillLevel",
            fields=[
                ("drill_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("level_index", models.PositiveSmallIntegerField()),
                ("min_gbp", models.DecimalField(decimal_places=4, max_digits=12)),
                ("max_gbp", models.DecimalField(decimal_places=4, max_digits=12)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drill_levels",
                        to="pricing.marketresearchsession",
                    ),
                ),
            ],
            options={
                "db_table": "pricing_market_research_drill_level",
                "ordering": ["level_index"],
            },
        ),
        migrations.AddConstraint(
            model_name="marketresearchsession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("request_item__isnull", False), ("repricing_session_item__isnull", True)),
                    models.Q(("request_item__isnull", True), ("repricing_session_item__isnull", False)),
                    _connector="OR",
                ),
                name="market_research_session_parent_xor",
            ),
        ),
        migrations.AddConstraint(
            model_name="marketresearchsession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("request_item__isnull", False)),
                fields=("request_item", "platform"),
                name="uniq_request_item_market_research_platform",
            ),
        ),
        migrations.AddConstraint(
            model_name="marketresearchsession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("repricing_session_item__isnull", False)),
                fields=("repricing_session_item", "platform"),
                name="uniq_repricing_item_market_research_platform",
            ),
        ),
        migrations.AddConstraint(
            model_name="marketresearchdrilllevel",
            constraint=models.UniqueConstraint(
                fields=("session", "level_index"),
                name="uniq_research_drill_session_level",
            ),
        ),
        migrations.RunPython(forwards_migrate, backwards_noop),
        migrations.RemoveField(
            model_name="repricingsessionitem",
            name="cash_converters_data",
        ),
        migrations.RemoveField(
            model_name="repricingsessionitem",
            name="raw_data",
        ),
        migrations.RemoveField(
            model_name="requestitem",
            name="cash_converters_data",
        ),
        migrations.RemoveField(
            model_name="requestitem",
            name="raw_data",
        ),
    ]
