# Generated by Django 6.0.2 on 2026-03-30 12:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0040_request_jewellery_reference_scrape'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestItemJewellery',
            fields=[
                ('request_item', models.OneToOneField(db_column='request_item_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='jewellery', serialize=False, to='pricing.requestitem')),
                ('measured_gross_weight_grams', models.DecimalField(blank=True, decimal_places=3, help_text='Canonical gross weight in grams used for valuation', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('measured_net_weight_grams', models.DecimalField(blank=True, decimal_places=3, help_text='Optional net precious-metal weight in grams', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('measured_stone_weight_grams', models.DecimalField(blank=True, decimal_places=3, help_text='Optional stone/non-metal deduction in grams', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('input_weight_value', models.DecimalField(blank=True, decimal_places=3, help_text='Original entered weight value before normalization', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('input_weight_unit', models.CharField(choices=[('g', 'Grams'), ('kg', 'Kilograms'), ('each', 'Each')], default='g', help_text='Original entry unit from UI/input form', max_length=10)),
                ('measurement_source', models.CharField(choices=[('MANUAL', 'Manual'), ('SCALE', 'Scale'), ('IMPORTED', 'Imported'), ('ESTIMATED', 'Estimated')], db_index=True, default='MANUAL', help_text='How this jewellery measurement was captured', max_length=20)),
                ('measured_by_name', models.CharField(blank=True, help_text='Staff member who captured this request-line measurement', max_length=255, null=True)),
                ('measured_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this request-line jewellery measurement was captured')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory_unit', models.ForeignKey(blank=True, help_text='Optional linked inventory unit once this request line is booked into stock', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_item_jewellery_rows', to='pricing.inventoryunit')),
                ('material_grade', models.ForeignKey(blank=True, db_column='material_grade_attribute_value_id', help_text='Material/purity grade (expected to reference the jewellery material_grade attribute)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_item_jewellery_rows', to='pricing.attributevalue')),
            ],
            options={
                'db_table': 'buying_request_item_jewellery',
            },
        ),
        migrations.CreateModel(
            name='InventoryUnitJewellery',
            fields=[
                ('inventory_unit', models.OneToOneField(db_column='inventory_item_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='jewellery', serialize=False, to='pricing.inventoryunit')),
                ('gross_weight_grams', models.DecimalField(db_index=True, decimal_places=3, help_text='Canonical gross stock weight in grams', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('net_weight_grams', models.DecimalField(blank=True, db_index=True, decimal_places=3, help_text='Optional net precious-metal weight in grams', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('stone_weight_grams', models.DecimalField(blank=True, decimal_places=3, help_text='Optional stone/non-metal deduction in grams', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('hallmark_status', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('UNREADABLE', 'Unreadable')], db_index=True, default='UNKNOWN', max_length=20)),
                ('measurement_source', models.CharField(choices=[('MANUAL', 'Manual'), ('SCALE', 'Scale'), ('IMPORTED', 'Imported'), ('ESTIMATED', 'Estimated')], db_index=True, default='MANUAL', help_text='How this stock-unit jewellery measurement was captured', max_length=20)),
                ('measured_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('measured_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material_grade', models.ForeignKey(blank=True, db_column='material_grade_attribute_value_id', help_text='Material/purity grade used for stock reporting and filtering', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_jewellery_rows', to='pricing.attributevalue')),
                ('source_request_item', models.ForeignKey(blank=True, help_text='Optional provenance link back to the request-line jewellery snapshot', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_units_created', to='pricing.requestitemjewellery')),
            ],
            options={
                'db_table': 'pricing_inventory_item_jewellery',
            },
        ),
        migrations.AddIndex(
            model_name='requestitemjewellery',
            index=models.Index(fields=['material_grade', 'measured_gross_weight_grams'], name='buying_requ_materia_4480b8_idx'),
        ),
        migrations.AddIndex(
            model_name='requestitemjewellery',
            index=models.Index(fields=['measured_at'], name='buying_requ_measure_9a3951_idx'),
        ),
        migrations.AddIndex(
            model_name='requestitemjewellery',
            index=models.Index(fields=['measurement_source'], name='buying_requ_measure_e6e07f_idx'),
        ),
        migrations.AddConstraint(
            model_name='requestitemjewellery',
            constraint=models.CheckConstraint(condition=models.Q(('measured_gross_weight_grams__isnull', True), ('measured_gross_weight_grams__gt', 0), _connector='OR'), name='req_item_jewellery_gross_weight_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='requestitemjewellery',
            constraint=models.CheckConstraint(condition=models.Q(('measured_net_weight_grams__isnull', True), ('measured_net_weight_grams__gte', 0), _connector='OR'), name='req_item_jewellery_net_weight_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='requestitemjewellery',
            constraint=models.CheckConstraint(condition=models.Q(('measured_stone_weight_grams__isnull', True), ('measured_stone_weight_grams__gte', 0), _connector='OR'), name='req_item_jewellery_stone_weight_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='requestitemjewellery',
            constraint=models.CheckConstraint(condition=models.Q(('measured_net_weight_grams__isnull', True), ('measured_gross_weight_grams__isnull', True), ('measured_net_weight_grams__lte', models.F('measured_gross_weight_grams')), _connector='OR'), name='req_item_jewellery_net_lte_gross'),
        ),
        migrations.AddConstraint(
            model_name='requestitemjewellery',
            constraint=models.CheckConstraint(condition=models.Q(('measured_stone_weight_grams__isnull', True), ('measured_gross_weight_grams__isnull', True), ('measured_stone_weight_grams__lte', models.F('measured_gross_weight_grams')), _connector='OR'), name='req_item_jewellery_stone_lte_gross'),
        ),
        migrations.AddIndex(
            model_name='inventoryunitjewellery',
            index=models.Index(fields=['material_grade', 'gross_weight_grams'], name='pricing_inv_materia_1fb60e_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryunitjewellery',
            index=models.Index(fields=['gross_weight_grams'], name='pricing_inv_gross_w_5bb25b_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryunitjewellery',
            index=models.Index(fields=['net_weight_grams'], name='pricing_inv_net_wei_cacd80_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryunitjewellery',
            index=models.Index(fields=['hallmark_status'], name='pricing_inv_hallmar_b503eb_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventoryunitjewellery',
            constraint=models.CheckConstraint(condition=models.Q(('gross_weight_grams__gt', 0)), name='inventory_jewellery_gross_weight_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='inventoryunitjewellery',
            constraint=models.CheckConstraint(condition=models.Q(('net_weight_grams__isnull', True), ('net_weight_grams__gte', 0), _connector='OR'), name='inventory_jewellery_net_weight_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='inventoryunitjewellery',
            constraint=models.CheckConstraint(condition=models.Q(('stone_weight_grams__isnull', True), ('stone_weight_grams__gte', 0), _connector='OR'), name='inventory_jewellery_stone_weight_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='inventoryunitjewellery',
            constraint=models.CheckConstraint(condition=models.Q(('net_weight_grams__isnull', True), ('net_weight_grams__lte', models.F('gross_weight_grams')), _connector='OR'), name='inventory_jewellery_net_lte_gross'),
        ),
        migrations.AddConstraint(
            model_name='inventoryunitjewellery',
            constraint=models.CheckConstraint(condition=models.Q(('stone_weight_grams__isnull', True), ('stone_weight_grams__lte', models.F('gross_weight_grams')), _connector='OR'), name='inventory_jewellery_stone_lte_gross'),
        ),
    ]
