# Generated by Django 6.0.2 on 2026-03-30 12:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0042_backfill_request_item_jewellery_from_reference_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestJewelleryReferenceSnapshot',
            fields=[
                ('snapshot_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source_name', models.CharField(blank=True, default='Mastermelt', help_text='Human-readable source system name', max_length=100)),
                ('source_url', models.URLField(blank=True, default='', max_length=2000)),
                ('scraped_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sections_json', models.JSONField(help_text='Normalized jewellery reference sections payload')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jewellery_reference_history', to='pricing.request')),
            ],
            options={
                'db_table': 'buying_request_jewellery_reference_snapshot',
            },
        ),
        migrations.CreateModel(
            name='RequestItemJewelleryValuation',
            fields=[
                ('valuation_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('valuation_source', models.CharField(db_index=True, help_text='Valuation source identifier (e.g., Mastermelt/manual/internal)', max_length=64)),
                ('rate_per_gram_gbp', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('unit_price_gbp', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('basis_weight_grams', models.DecimalField(blank=True, decimal_places=3, help_text='Weight basis used in this valuation snapshot', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('computed_total_gbp', models.DecimalField(decimal_places=2, help_text='Computed valuation total for this snapshot', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('valuation_payload_json', models.JSONField(blank=True, help_text='Raw valuation payload for reproducibility/audit', null=True)),
                ('is_selected', models.BooleanField(db_index=True, default=False, help_text='True when this valuation is currently selected for the request line')),
                ('selected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('request_item_jewellery', models.ForeignKey(db_column='request_item_id', on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='pricing.requestitemjewellery')),
                ('source_reference_snapshot', models.ForeignKey(blank=True, help_text='Optional request-level reference snapshot used for this valuation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valuations', to='pricing.requestjewelleryreferencesnapshot')),
            ],
            options={
                'db_table': 'buying_request_item_jewellery_valuation',
            },
        ),
        migrations.AddField(
            model_name='request',
            name='current_jewellery_reference_snapshot',
            field=models.ForeignKey(blank=True, help_text='Currently selected jewellery reference snapshot for this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_requests', to='pricing.requestjewelleryreferencesnapshot'),
        ),
        migrations.AddIndex(
            model_name='requestjewelleryreferencesnapshot',
            index=models.Index(fields=['request', '-created_at'], name='buying_requ_request_31bfed_idx'),
        ),
        migrations.AddIndex(
            model_name='requestjewelleryreferencesnapshot',
            index=models.Index(fields=['request', '-scraped_at'], name='buying_requ_request_c629aa_idx'),
        ),
        migrations.AddIndex(
            model_name='requestitemjewelleryvaluation',
            index=models.Index(fields=['request_item_jewellery', '-created_at'], name='buying_requ_request_5e8a50_idx'),
        ),
        migrations.AddIndex(
            model_name='requestitemjewelleryvaluation',
            index=models.Index(fields=['valuation_source', '-created_at'], name='buying_requ_valuati_22d365_idx'),
        ),
        migrations.AddIndex(
            model_name='requestitemjewelleryvaluation',
            index=models.Index(fields=['computed_total_gbp'], name='buying_requ_compute_cb94f1_idx'),
        ),
        migrations.AddConstraint(
            model_name='requestitemjewelleryvaluation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_selected', True)), fields=('request_item_jewellery',), name='uniq_selected_jewellery_valuation_per_request_item'),
        ),
        migrations.AddConstraint(
            model_name='requestitemjewelleryvaluation',
            constraint=models.CheckConstraint(condition=models.Q(('computed_total_gbp__gte', 0)), name='req_item_jewellery_valuation_total_gte_zero'),
        ),
    ]
