# Generated by Django 6.0.2 on 2026-03-30 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0044_backfill_jewellery_reference_history_and_valuations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='jewellery_reference_scrape_json',
        ),
    ]
