# Generated by Django 6.0.2 on 2026-03-30 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0051_drop_legacy_identity_and_selection_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='requestitemoffer',
            new_name='buying_requ_request_7b7d22_idx',
            old_name='buying_requ_request_4e24fb_idx',
        ),
        migrations.RenameIndex(
            model_name='requestitemoffer',
            new_name='buying_requ_request_7e00cb_idx',
            old_name='buying_requ_request_bca574_idx',
        ),
    ]
