# Generated by Django 6.0.2 on 2026-03-31 12:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0053_jewellery_coin_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOfferRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(choices=[('new_customer', 'New Customer'), ('low_cr', 'Low Cancel Rate'), ('mid_cr', 'Mid Cancel Rate'), ('high_cr', 'High Cancel Rate')], help_text='The customer classification this rule applies to.', max_length=20, unique=True)),
                ('allow_offer_1', models.BooleanField(default=True, help_text='Whether the 1st Offer slot can be selected without authorisation.')),
                ('allow_offer_2', models.BooleanField(default=True, help_text='Whether the 2nd Offer slot can be selected without authorisation.')),
                ('allow_offer_3', models.BooleanField(default=True, help_text='Whether the 3rd Offer slot can be selected without authorisation.')),
                ('allow_offer_4', models.BooleanField(default=True, help_text='Whether the 4th Offer slot (Match CeX) can be selected without authorisation.')),
                ('allow_manual', models.BooleanField(default=True, help_text='Whether a manual offer entry is allowed without authorisation.')),
            ],
            options={
                'verbose_name': 'Customer Offer Rule',
                'verbose_name_plural': 'Customer Offer Rules',
                'db_table': 'buying_customer_offer_rule',
            },
        ),
        migrations.CreateModel(
            name='CustomerRuleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_cr_max_pct', models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text="Upper bound (inclusive) for the 'Low Cancel Rate' tier. Customers with cancel rate ≤ this value are classified as Low CR.", max_digits=6)),
                ('mid_cr_max_pct', models.DecimalField(decimal_places=2, default=Decimal('40.00'), help_text="Upper bound (inclusive) for the 'Mid Cancel Rate' tier. Customers with cancel rate between Low CR max and this value are Mid CR; above this value is High CR.", max_digits=6)),
            ],
            options={
                'verbose_name': 'Customer Rule Settings',
                'db_table': 'buying_customer_rule_settings',
            },
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='third_offer_pct_of_cex',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='% of the CeX trade-in price offered as the Third Offer. E.g. 100 means offer_3 = cex_tradein * 1.00 (matches CeX). Leave blank to default to 100% (match CeX trade-in exactly).', max_digits=5, null=True),
        ),
    ]
