# Generated by Django 6.0.2 on 2026-04-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0062_nosposcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerofferrule',
            name='allow_offer_4',
            field=models.BooleanField(default=True, help_text='Whether the 4th Offer slot can be selected without authorisation.'),
        ),
        migrations.AlterField(
            model_name='nosposcategorymapping',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
