# Generated by Django 6.0.2 on 2026-04-07 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0069_request_park_agreement_state_json'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nosposfield',
            options={'ordering': ['nospos_field_id'], 'verbose_name': 'NosPos field', 'verbose_name_plural': 'NosPos fields'},
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='ready_for_builder',
            field=models.BooleanField(db_index=True, default=True, help_text='If False, hide this category (and use only where full tree is needed, e.g. NosPos mapping / data tools). Buyer and repricing sidebars only show categories with this True.'),
        ),
        migrations.AlterField(
            model_name='request',
            name='park_agreement_state_json',
            field=models.JSONField(blank=True, help_text='Park agreement: NosPos items URL, excluded line ids, progress modal snapshot (in-store testing)', null=True),
        ),
    ]
