# Generated by Django 6.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0070_alter_nosposfield_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketresearchdrilllevel",
            name="segments_json",
            field=models.JSONField(
                blank=True,
                help_text="When set, OR of [{min, max}, ...] price bands (multi-zoom). min_gbp/max_gbp store the envelope.",
                null=True,
            ),
        ),
    ]
