# Generated by Django 6.0.4 on 2026-04-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0071_marketresearchdrilllevel_segments_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketresearchsession',
            name='platform',
            field=models.CharField(choices=[('EBAY', 'eBay'), ('CASH_CONVERTERS', 'Cash Converters'), ('CASH_GENERATOR', 'Cash Generator')], db_index=True, max_length=32),
        ),
    ]
