# Generated by Django 6.0.4 on 2026-04-14 16:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0072_marketresearch_platform_cash_generator'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('upload_session_id', models.AutoField(primary_key=True, serialize=False)),
                ('cart_key', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('barcode_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], db_index=True, default='IN_PROGRESS', max_length=20)),
                ('session_data', models.JSONField(blank=True, help_text='Full frontend state for resuming upload sessions (items, barcodes, lookups, research)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pricing_upload_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadSessionItem',
            fields=[
                ('item_identifier', models.CharField(blank=True, default='', max_length=100)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('barcode', models.CharField(db_index=True, max_length=255)),
                ('stock_barcode', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('stock_url', models.URLField(blank=True, default='', help_text='Link to the stock page in NoSPos / stock system', max_length=500)),
                ('old_retail_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('new_retail_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cex_sell_at_repricing', models.DecimalField(blank=True, decimal_places=2, help_text='CeX sell snapshot at workflow time (repricing or upload)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('our_sale_price_at_repricing', models.DecimalField(blank=True, decimal_places=2, help_text='Our sale / new retail input at workflow time (repricing or upload)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('upload_session_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pricing_upload_session_item',
                'ordering': ['upload_session_item_id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='marketresearchsession',
            name='market_research_session_parent_xor',
        ),
        migrations.AlterField(
            model_name='repricingsessionitem',
            name='cex_sell_at_repricing',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='CeX sell snapshot at workflow time (repricing or upload)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='repricingsessionitem',
            name='our_sale_price_at_repricing',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Our sale / new retail input at workflow time (repricing or upload)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='uploadsessionitem',
            name='upload_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pricing.uploadsession'),
        ),
        migrations.AddField(
            model_name='marketresearchsession',
            name='upload_session_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market_research_sessions', to='pricing.uploadsessionitem'),
        ),
        migrations.AddConstraint(
            model_name='marketresearchsession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('request_item__isnull', False), ('repricing_session_item__isnull', True), ('upload_session_item__isnull', True)), models.Q(('request_item__isnull', True), ('repricing_session_item__isnull', False), ('upload_session_item__isnull', True)), models.Q(('request_item__isnull', True), ('repricing_session_item__isnull', True), ('upload_session_item__isnull', False)), _connector='OR'), name='market_research_session_parent_xor'),
        ),
        migrations.AddConstraint(
            model_name='marketresearchsession',
            constraint=models.UniqueConstraint(condition=models.Q(('upload_session_item__isnull', False)), fields=('upload_session_item', 'platform'), name='uniq_upload_session_item_market_research_platform'),
        ),
    ]
