# Generated by Django 6.0.1 on 2026-04-16 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0073_upload_session_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='CgCategory',
            fields=[
                ('cg_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('parent_category', models.ForeignKey(blank=True, db_column='parent_category_id', help_text='Parent category. Root categories have this empty.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pricing.cgcategory')),
            ],
            options={
                'verbose_name': 'CG category',
                'verbose_name_plural': 'CG categories',
                'db_table': 'pricing_cg_category',
                'indexes': [models.Index(fields=['parent_category', 'name'], name='pricing_cg__parent__372ff6_idx')],
            },
        ),
    ]
