# Generated by Django 6.0.1 on 2026-04-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0074_cg_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cgcategory',
            name='collection_slug',
            field=models.CharField(blank=True, db_index=True, help_text='Stable id from Cash Generator ?collection=… (or synthetic if URL missing).', max_length=512, null=True, unique=True),
        ),
    ]
