# Generated by Django 6.0.1 on 2026-04-26 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0075_cg_category_collection_slug'),
        ('pricing', '0078_webepos_categories'),
    ]

    operations = [
    ]
